### ISSUE TITLE
Install Error - Won't Initialize with Automatic Detection

### ISSUE THREAD

**Issue by tylas13** [gdgib/span#13]
After getting another lock-out due to the door panel needing to be opened x3 again I attempted reinstall, but integration would not initialize using the automatic detection feature in the Devices and Services section in Settings.  Would get an access token error:

```
Logger: homeassistant.config_entries
Source: custom_components/span_panel/__init__.py:40 
Integration: Span Panel ([documentation](https://github.com/gdgib/span), [issues](https://github.com/gdgib/span/issues)) 
First occurred: 1:19:03 PM (1 occurrences) 
Last logged: 1:19:03 PM

Error setting up entry Span Panel nt-2142-c1aj0 for span_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/span_panel/__init__.py", line 40, in async_setup_entry
    access_token=config[CONF_ACCESS_TOKEN],
KeyError: 'access_token'
```

If I choose a manual installation it installs flawlessly and begins logging data.  However, the Devices and Services will still see the Span Panel to do a setup even though it is already configured.

**Comment by etmelvin** [comment]
Duplicated discovery and set up from discovery should be fixed with this PR

https://github.com/gdgib/span/pull/12

**Comment by sargonas** [comment]
@tylas13 I'm doing some volunteer support housekeeping on a few HA-related repos that I rely on and wanted to check in on this one. Did the newer version using the merged-in PR 12 listed above prevent this issue from reoccurring for you, and if so is it safe to close this one out?

**Comment by qwertyphile** [comment]
Had this exact issue just now... The default version from the HACS dropdown is 'v0.0.7' and I resolved the issue by manually choosing the 'main' branch in HACS durring the download stage.

All is good now that I'm on the 'main' branch.

**Comment by tylas13** [comment]
Yes, I do still have this issue. Had do to a reset again with the door swing open x 3 times this weekend and usually have to reinstall the integration.  The auto detect install does not register but if you go into the <Add Integration> button and put in the IP address this will work as expected. 

I have not attempted to reinstall the integration from HACS. I am using gdgib's 0.0.7 version - don't know if it if 'main' branch or not.

**Comment by sargonas** [comment]
Yeah this should be fixed, but you need to run a different version. Here's how:

1. Go into the HACS panel menu and select the span integration.
2. Once you are inside the span integration (where all the readme data is) click the three dots in the top right, and select "Redownload".
3. On the new box that appears, the dropdown for "select version" will be pre set to `v0.0.7`. You want to click thsi drop down and scroll to the bottom, where the last entry says `main`. Select that, and click download to update your version to the `main` version.
This should replace your version of the Span integration with one that has new code changes that should solve your issue. In the future when version `0.0.8` is eventually released, you can update to that instead if you like, and continue following the latest releases from that point.

(Context: `0.0.7` is the most recent release, `main` is everything that has been added to the code _since_ `0.0.7`, but has not yet made it into a future pending `0.0.8`)

**Comment by tylas13** [comment]
Thanks for the instructions, thought I was on the most recent version and missed the ‘main’ on the bottom. 

Had to delete the integration, redownload, restart (twice for some reason?) and then auto detect enrolled it without an issue.  

Thanks all!

**Comment by sargonas** [comment]
Technically you were on the latest "Release" which is what you generally want to be on. `Main` is sort of a rolling version of the "bleeding edge" of what *will* be in the next release once it is ready... so this was just a shortcut way to get you those fixes you needed before a `0.0.8` release is cut.
